agent:
  api_url: "http://127.0.0.1:8000"
  total_steps: 10
  total_time_limit: 7200
  time_limit_per_step: 1800
  working_dir: "./workspace"
  
llm:
  model_name: "o4-mini-2025-04-16"
  api_key: "unspecified"
  temperature: 1.0
  max_tokens: 100000
  timeout: 600
  native_function_calling: true
  keep_history: true

docker:
  image: "comind-agent"
  gpu: "all"

input_dir: "./competition/aerial-cactus-identification/input"
